name: Unit Tests - PR
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  all_unit_tests:
    name: "All Unit Tests"
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci/skip-unit') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            tcons,
            tcons-cli,
            "@tcons/hcl2cdk",
            "@tcons/hcl2json",
            "@tcons/provider-schema",
            "@tcons/provider-generator",
            "@tcons/commons",
            "@tcons/cli-core",
          ]
        terraform_version: ["1.6.5", "1.5.5"]
    with:
      concurrency_group_prefix: pr-all
      package: ${{ matrix.package }}
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  cdktf_cli_core:
    name: "@cdktf/cli Unit Tests"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-unit/@cdktf/cli-core') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.6.5"]
    with:
      concurrency_group_prefix: pr-cdktf-cli-core
      package: "@tcons/cli-core"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  cdktf_commons:
    name: "@cdktf/commons Unit Tests"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-unit/@cdktf/commons') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.6.5"]
    with:
      concurrency_group_prefix: pr-cdktf-commons
      package: "@tcons/commons"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  cdktf_hcl2cdk:
    name: "@cdktf/hcl2cdk Unit Tests"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-unit/@cdktf/hcl2cdk') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.6.5"]
    with:
      concurrency_group_prefix: pr-cdktf-hcl2cdk
      package: "@tcons/hcl2cdk"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  cdktf_hcl2json:
    name: "@cdktf/hcl2json Unit Tests"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-unit/@cdktf/hcl2json') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.6.5"]
    with:
      concurrency_group_prefix: pr-cdktf-hcl2json
      package: "@tcons/hcl2json"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  cdktf_provider_generator:
    name: "@cdktf/provider-generator Unit Tests"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-unit/@cdktf/provider-generator') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.6.5"]
    with:
      concurrency_group_prefix: pr-cdktf-provider-generator
      package: "@tcons/provider-generator"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  cdktf_cli:
    name: "cdktf-cli Unit Tests"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-unit/cdktf-cli') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.6.5"]
    with:
      concurrency_group_prefix: pr-cdktf-cli
      package: "tcons-cli"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  cdktf:
    name: "cdktf Unit Tests"
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-unit/cdktf') }}
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.6.5"]
    with:
      concurrency_group_prefix: pr-cdktf
      package: "tcons"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit

  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Unit Tests - PR - Result
    needs:
      [
        all_unit_tests,
        cdktf,
        cdktf_cli,
        cdktf_provider_generator,
        cdktf_hcl2json,
        cdktf_hcl2cdk,
        cdktf_commons,
        cdktf_cli_core,
      ]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
